### ISSUE TITLE
feat : 사진작가 api 구현

### ISSUE THREAD

**Issue by khgeung** [CUKCatSnap/CUKCATSNAP_Web#1]
## 💡 Feature Issue
모델-사진작가 중 사진작가와 관련된 api를 연결한다.

## 🌿  To-do

- [x] 작가가 자신의 예약 설정을 조회하는 api (getSetting)
- [x] 작가가 자신의 예약 전 알림을 조회하는 api (getAuthorReservationAlarm)
- [x] 작가가 자신이 예약을 받을 장소를 조회하는 api  (getAuthorSettingPlace)
