### ISSUE TITLE
feat : 사진작가 관련 api post 설정

### ISSUE THREAD

**Issue by khgeung** [CUKCatSnap/CUKCATSNAP_Web#5]
## 💡 Feature Issue
사진 작가의 환경 설정에서 예약 관련 api를 연결한다.

## 🌿  To-do

- [x] 작가가 자신의 예약 설정을 수정하는 api 
- [x] 작가가 자신의 예약 전 알림을 수정하는 api
- [x] 작가가 자신이 예약을 받을 장소를 수정하는 api
